variables:
  # buster is based on the v2.x branch and not master
  SKIP_RELEASE_PATTERN: /buster/

# Avoid duplicate pipelines
# See: https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"
    - if: "$CI_COMMIT_TAG"

# Build a snapshot debian package from current master
include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/package-build-raspios-snapshot.yml"
  - local: debian/gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^raspios\/.*/
        exists:
          - debian/gitlab-ci.yml

# build the repo
test-build-cmake:
  image: registry.gitlab.com/revolutionpi/infrastructure/docker-images/build-container/build-container-bullseye:arm64-latest
  tags:
    - docker
    - host-arm64
  stage: build
  script:
    - apt update
    - apt install -y cmake pkg-config systemd udev libftdi1-dev xxd
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
